import type { Template } from '@/types';
import { generateId } from '@/lib/utils';

export const templates: Template[] = [
  // Minimal Portfolio
  {
    id: 'minimal-portfolio',
    name: 'Minimal Portfolio',
    description: 'Clean and simple portfolio for creatives',
    thumbnail: '/templates/minimal.png',
    category: 'minimal',
    settings: {
      title: 'My Portfolio',
      description: 'A personal portfolio website',
      theme: {
        mode: 'light',
        primaryColor: '#000000',
        secondaryColor: '#6b7280',
        backgroundColor: '#ffffff',
        textColor: '#000000',
        accentColor: '#0ea5e9',
      },
      fonts: {
        heading: 'Inter, -apple-system, sans-serif',
        body: 'Inter, -apple-system, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'Hi, I\'m Alex',
          subheadline: 'Designer & Developer creating digital experiences',
          buttonText: 'View My Work',
          buttonLink: '#projects',
          showButton: true,
        },
        style: {
          backgroundColor: '#ffffff',
          textColor: '#000000',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'about',
        order: 1,
        content: {
          title: 'About',
          description: 'I\'m a designer and developer with 5+ years of experience creating digital products. I focus on clean design, smooth interactions, and solving real problems.',
          showImage: false,
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'narrow',
        },
      },
      {
        id: generateId(),
        type: 'projects',
        order: 2,
        content: {
          title: 'Selected Work',
          projects: [
            { title: 'Brand Redesign', description: 'Complete visual identity for tech startup', image: '', link: '#', tags: ['Branding', 'Design'] },
            { title: 'Mobile App', description: 'iOS app for fitness tracking', image: '', link: '#', tags: ['UI/UX', 'Mobile'] },
            { title: 'E-commerce Site', description: 'Full-stack online store', image: '', link: '#', tags: ['Development', 'Design'] },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'contact',
        order: 3,
        content: {
          title: 'Let\'s Talk',
          subtitle: 'Have a project in mind? Let\'s create something great together.',
          email: 'hello@example.com',
          buttonText: 'Send Message',
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'narrow',
        },
      },
    ],
  },
  // Creative Portfolio
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    description: 'Bold and colorful design for artists',
    thumbnail: '/templates/creative.png',
    category: 'creative',
    settings: {
      title: 'Creative Portfolio',
      description: 'A bold creative portfolio',
      theme: {
        mode: 'dark',
        primaryColor: '#a855f7',
        secondaryColor: '#ec4899',
        backgroundColor: '#0f172a',
        textColor: '#ffffff',
        accentColor: '#a855f7',
      },
      fonts: {
        heading: 'Inter, sans-serif',
        body: 'Inter, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'Creative Mind',
          subheadline: 'Turning ideas into visual stories',
          buttonText: 'Explore',
          buttonLink: '#gallery',
          showButton: true,
        },
        style: {
          backgroundColor: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)',
          textColor: '#ffffff',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'gallery',
        order: 1,
        content: {
          title: 'Gallery',
          images: [
            { src: '', alt: 'Art 1', caption: 'Abstract Dreams' },
            { src: '', alt: 'Art 2', caption: 'Color Theory' },
            { src: '', alt: 'Art 3', caption: 'Digital Art' },
            { src: '', alt: 'Art 4', caption: 'Illustrations' },
            { src: '', alt: 'Art 5', caption: 'Photography' },
            { src: '', alt: 'Art 6', caption: 'Mixed Media' },
          ],
          columns: 3,
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
          borderRadius: 'large',
        },
      },
      {
        id: generateId(),
        type: 'cta',
        order: 2,
        content: {
          headline: 'Let\'s Create Together',
          description: 'Available for commissions and collaborations',
          primaryButtonText: 'Get in Touch',
          primaryButtonLink: '#contact',
          showSecondaryButton: false,
        },
        style: {
          backgroundColor: '#a855f7',
          textColor: '#ffffff',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
    ],
  },
  // SaaS Landing Page
  {
    id: 'saas-landing',
    name: 'SaaS Landing',
    description: 'Modern landing page for software products',
    thumbnail: '/templates/saas.png',
    category: 'business',
    settings: {
      title: 'SaaS Product',
      description: 'Modern SaaS landing page',
      theme: {
        mode: 'light',
        primaryColor: '#6366f1',
        secondaryColor: '#8b5cf6',
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        accentColor: '#6366f1',
      },
      fonts: {
        heading: 'Inter, sans-serif',
        body: 'Inter, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'navigation',
        order: 0,
        content: {
          logo: 'Productify',
          logoUrl: '',
          links: [
            { label: 'Features', url: '#features' },
            { label: 'Pricing', url: '#pricing' },
            { label: 'About', url: '#about' },
            { label: 'Contact', url: '#contact' },
          ],
          sticky: true,
          showCta: true,
          ctaText: 'Get Started',
          ctaUrl: '#pricing',
        },
        style: {
          backgroundColor: '#ffffff',
          textColor: '#1e293b',
          padding: 'small',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        order: 1,
        content: {
          headline: 'Build Products Faster',
          subheadline: 'The all-in-one platform for modern teams. Streamline workflows, collaborate seamlessly, and ship faster.',
          buttonText: 'Start Free Trial',
          buttonLink: '#pricing',
          showButton: true,
        },
        style: {
          backgroundColor: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%)',
          textColor: '#ffffff',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'stats',
        order: 2,
        content: {
          title: '',
          subtitle: '',
          stats: [
            { value: 10000, suffix: '+', label: 'Active Users' },
            { value: 99, suffix: '%', label: 'Uptime' },
            { value: 50, suffix: '+', label: 'Integrations' },
            { value: 24, suffix: '/7', label: 'Support' },
          ],
          animateOnView: true,
          duration: 2000,
        },
        style: {
          backgroundColor: '#f8fafc',
          textColor: '#1e293b',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'features',
        order: 3,
        content: {
          title: 'Everything You Need',
          subtitle: 'Powerful features to help your team succeed',
          features: [
            { icon: 'Zap', title: 'Lightning Fast', description: 'Optimized for speed and performance' },
            { icon: 'Shield', title: 'Secure by Default', description: 'Enterprise-grade security built in' },
            { icon: 'Globe', title: 'Global Scale', description: 'Deploy worldwide in seconds' },
            { icon: 'Users', title: 'Team Collaboration', description: 'Work together seamlessly' },
            { icon: 'Code', title: 'Developer Friendly', description: 'APIs and webhooks included' },
            { icon: 'Sparkles', title: 'AI Powered', description: 'Smart automation at your fingertips' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'pricing',
        order: 4,
        content: {
          title: 'Simple, Transparent Pricing',
          subtitle: 'Start free, upgrade when you\'re ready',
          plans: [
            {
              name: 'Starter',
              price: '$0',
              period: '/month',
              description: 'Perfect for trying out',
              features: ['5 Projects', '1GB Storage', 'Community Support', 'Basic Analytics'],
              buttonText: 'Get Started',
              buttonUrl: '#',
              highlighted: false,
            },
            {
              name: 'Pro',
              price: '$29',
              period: '/month',
              description: 'For growing teams',
              features: ['Unlimited Projects', '100GB Storage', 'Priority Support', 'Advanced Analytics', 'Custom Domain', 'API Access'],
              buttonText: 'Start Free Trial',
              buttonUrl: '#',
              highlighted: true,
            },
            {
              name: 'Enterprise',
              price: 'Custom',
              period: '',
              description: 'For large organizations',
              features: ['Everything in Pro', 'Unlimited Storage', 'Dedicated Support', 'Custom Integrations', 'SLA Guarantee', 'SSO'],
              buttonText: 'Contact Sales',
              buttonUrl: '#',
              highlighted: false,
            },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'testimonials',
        order: 5,
        content: {
          title: 'Loved by Teams Worldwide',
          testimonials: [
            { quote: 'This product transformed how our team works. We\'re 10x more productive.', author: 'Sarah Chen', role: 'CTO, TechStart', avatar: '' },
            { quote: 'The best investment we\'ve made for our workflow. Simply amazing.', author: 'Mike Johnson', role: 'CEO, GrowthCo', avatar: '' },
            { quote: 'Finally, a tool that just works. No learning curve, instant value.', author: 'Emily Davis', role: 'PM, InnovateLab', avatar: '' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
          backgroundColor: '#f8fafc',
        },
      },
      {
        id: generateId(),
        type: 'faq',
        order: 6,
        content: {
          title: 'Frequently Asked Questions',
          subtitle: 'Got questions? We\'ve got answers.',
          items: [
            { question: 'How does the free trial work?', answer: 'Start with a 14-day free trial of our Pro plan. No credit card required.' },
            { question: 'Can I cancel anytime?', answer: 'Yes, you can cancel your subscription at any time with no penalties.' },
            { question: 'Do you offer refunds?', answer: 'We offer a 30-day money-back guarantee on all paid plans.' },
            { question: 'What integrations do you support?', answer: 'We integrate with 50+ popular tools including Slack, GitHub, Jira, and more.' },
          ],
          allowMultiple: false,
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'cta',
        order: 7,
        content: {
          headline: 'Ready to Get Started?',
          description: 'Join thousands of teams already using our platform.',
          primaryButtonText: 'Start Free Trial',
          primaryButtonLink: '#',
          secondaryButtonText: 'Talk to Sales',
          secondaryButtonLink: '#contact',
          showSecondaryButton: true,
        },
        style: {
          backgroundColor: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
          textColor: '#ffffff',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'footer',
        order: 8,
        content: {
          logo: 'Productify',
          description: 'The modern platform for teams.',
          columns: [
            {
              title: 'Product',
              links: [
                { label: 'Features', url: '#' },
                { label: 'Pricing', url: '#' },
                { label: 'Integrations', url: '#' },
              ],
            },
            {
              title: 'Company',
              links: [
                { label: 'About', url: '#' },
                { label: 'Blog', url: '#' },
                { label: 'Careers', url: '#' },
              ],
            },
          ],
          copyright: '© 2024 Productify. All rights reserved.',
          showBackToTop: true,
          showSocial: true,
          socialLinks: [
            { platform: 'twitter', url: '#' },
            { platform: 'github', url: '#' },
            { platform: 'linkedin', url: '#' },
          ],
        },
        style: {
          backgroundColor: '#0f172a',
          textColor: '#ffffff',
          padding: 'large',
          width: 'full',
        },
      },
    ],
  },
  // Freelancer
  {
    id: 'freelancer',
    name: 'Freelancer',
    description: 'Personal brand for freelancers and consultants',
    thumbnail: '/templates/freelancer.png',
    category: 'portfolio',
    settings: {
      title: 'Freelancer Portfolio',
      description: 'Professional freelancer website',
      theme: {
        mode: 'light',
        primaryColor: '#f97316',
        secondaryColor: '#ea580c',
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        accentColor: '#f97316',
      },
      fonts: {
        heading: 'Inter, sans-serif',
        body: 'Inter, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'I Help Brands Tell Their Story',
          subheadline: 'Freelance designer and brand strategist with 8+ years helping startups and enterprises build memorable identities.',
          buttonText: 'Let\'s Work Together',
          buttonLink: '#contact',
          showButton: true,
        },
        style: {
          backgroundColor: '#fff7ed',
          textColor: '#1e293b',
          padding: 'large',
          alignment: 'left',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'features',
        order: 1,
        content: {
          title: 'Services',
          subtitle: 'What I can do for you',
          features: [
            { icon: 'Palette', title: 'Brand Identity', description: 'Complete visual identity systems from logo to guidelines' },
            { icon: 'Layout', title: 'Web Design', description: 'Beautiful, conversion-focused website designs' },
            { icon: 'Megaphone', title: 'Brand Strategy', description: 'Positioning and messaging that resonates' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'projects',
        order: 2,
        content: {
          title: 'Recent Projects',
          projects: [
            { title: 'Bloom Cosmetics', description: 'Brand identity and packaging design', image: '', link: '#', tags: ['Branding', 'Packaging'] },
            { title: 'TechFlow', description: 'SaaS product branding and website', image: '', link: '#', tags: ['SaaS', 'Web Design'] },
            { title: 'Urban Bites', description: 'Restaurant brand and menu design', image: '', link: '#', tags: ['Food', 'Print'] },
            { title: 'Mindful App', description: 'Meditation app branding', image: '', link: '#', tags: ['App', 'Wellness'] },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'testimonials',
        order: 3,
        content: {
          title: 'Client Love',
          testimonials: [
            { quote: 'Working with them was a game-changer for our brand. Exceeded all expectations!', author: 'Lisa Park', role: 'Founder, Bloom', avatar: '' },
            { quote: 'Incredible attention to detail and a true understanding of our vision.', author: 'James Miller', role: 'CEO, TechFlow', avatar: '' },
          ],
        },
        style: {
          backgroundColor: '#fff7ed',
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'contact',
        order: 4,
        content: {
          title: 'Start a Project',
          subtitle: 'Have an exciting project? Let\'s talk about how I can help bring your vision to life.',
          email: 'hello@freelancer.com',
          showPhone: true,
          phone: '+1 (555) 123-4567',
          buttonText: 'Send Message',
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
    ],
  },
  // Developer Portfolio
  {
    id: 'developer',
    name: 'Developer',
    description: 'Clean portfolio for software developers',
    thumbnail: '/templates/developer.png',
    category: 'portfolio',
    settings: {
      title: 'Developer Portfolio',
      description: 'Software developer portfolio',
      theme: {
        mode: 'dark',
        primaryColor: '#10b981',
        secondaryColor: '#059669',
        backgroundColor: '#0f172a',
        textColor: '#f8fafc',
        accentColor: '#10b981',
      },
      fonts: {
        heading: 'Inter, sans-serif',
        body: 'Inter, sans-serif',
        headingSize: 'medium',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'Full-Stack Developer',
          subheadline: 'I build scalable web applications with modern technologies. Currently open to new opportunities.',
          buttonText: 'View Projects',
          buttonLink: '#projects',
          showButton: true,
        },
        style: {
          backgroundColor: '#0f172a',
          textColor: '#f8fafc',
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'skills',
        order: 1,
        content: {
          title: 'Tech Stack',
          skills: [
            { name: 'React / Next.js', level: 95 },
            { name: 'TypeScript', level: 92 },
            { name: 'Node.js', level: 88 },
            { name: 'Python', level: 85 },
            { name: 'PostgreSQL / MongoDB', level: 82 },
            { name: 'AWS / Docker', level: 78 },
          ],
          showPercentage: true,
        },
        style: {
          padding: 'large',
          alignment: 'left',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'projects',
        order: 2,
        content: {
          title: 'Featured Projects',
          projects: [
            { title: 'CloudDeploy', description: 'CI/CD platform for modern teams', image: '', link: '#', tags: ['Next.js', 'AWS', 'Docker'] },
            { title: 'DataViz Pro', description: 'Real-time analytics dashboard', image: '', link: '#', tags: ['React', 'D3.js', 'WebSocket'] },
            { title: 'SecureAuth', description: 'Authentication microservice', image: '', link: '#', tags: ['Node.js', 'JWT', 'Redis'] },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'experience',
        order: 3,
        content: {
          title: 'Experience',
          items: [
            { year: '2022-Present', title: 'Senior Software Engineer', company: 'TechCorp', description: 'Leading frontend architecture' },
            { year: '2020-2022', title: 'Software Engineer', company: 'StartupXYZ', description: 'Full-stack development' },
            { year: '2018-2020', title: 'Junior Developer', company: 'WebAgency', description: 'Frontend development' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'left',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'contact',
        order: 4,
        content: {
          title: 'Get In Touch',
          subtitle: 'Open to freelance projects and full-time opportunities',
          email: 'dev@example.com',
          buttonText: 'Send Message',
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'narrow',
        },
      },
    ],
  },
  // Restaurant / Cafe
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Elegant template for restaurants and cafes',
    thumbnail: '/templates/restaurant.png',
    category: 'business',
    settings: {
      title: 'Restaurant',
      description: 'Restaurant website',
      theme: {
        mode: 'light',
        primaryColor: '#b91c1c',
        secondaryColor: '#991b1b',
        backgroundColor: '#fef2f2',
        textColor: '#1c1917',
        accentColor: '#b91c1c',
      },
      fonts: {
        heading: 'Georgia, serif',
        body: 'Inter, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'La Bella Cucina',
          subheadline: 'Authentic Italian cuisine crafted with passion and the finest ingredients since 1985',
          buttonText: 'View Menu',
          buttonLink: '#menu',
          showButton: true,
        },
        style: {
          backgroundColor: '#1c1917',
          textColor: '#fef2f2',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'about',
        order: 1,
        content: {
          title: 'Our Story',
          description: 'For over three decades, La Bella Cucina has been serving the community with recipes passed down through generations. Our commitment to quality ingredients and traditional cooking methods sets us apart.',
          showImage: true,
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'features',
        order: 2,
        content: {
          title: 'Menu Highlights',
          subtitle: 'Our most beloved dishes',
          features: [
            { icon: 'Utensils', title: 'Pasta Fresca', description: 'Handmade pasta daily with seasonal ingredients' },
            { icon: 'Wine', title: 'Fine Wines', description: 'Curated selection from Italian vineyards' },
            { icon: 'Cake', title: 'Dolci', description: 'Traditional desserts made in-house' },
          ],
        },
        style: {
          backgroundColor: '#fef2f2',
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'testimonials',
        order: 3,
        content: {
          title: 'What Guests Say',
          testimonials: [
            { quote: 'The best Italian food outside of Italy. An absolute gem!', author: 'Food & Wine Magazine', role: '', avatar: '' },
            { quote: 'Every dish tells a story. The tiramisu is heavenly.', author: 'Michael S.', role: 'Regular Guest', avatar: '' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'map',
        order: 4,
        content: {
          title: 'Visit Us',
          address: '123 Italian Street, Food District',
          latitude: 40.7128,
          longitude: -74.0060,
          zoom: 15,
          mapType: 'roadmap',
          showMarker: true,
          height: 350,
        },
        style: {
          padding: 'large',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'contact',
        order: 5,
        content: {
          title: 'Reservations',
          subtitle: 'Book your table for an unforgettable dining experience',
          email: 'reservations@labellacucina.com',
          showPhone: true,
          phone: '+1 (555) 234-5678',
          buttonText: 'Reserve a Table',
        },
        style: {
          backgroundColor: '#1c1917',
          textColor: '#fef2f2',
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
    ],
  },
  // Agency
  {
    id: 'agency',
    name: 'Agency',
    description: 'Bold template for creative agencies',
    thumbnail: '/templates/agency.png',
    category: 'business',
    settings: {
      title: 'Creative Agency',
      description: 'Digital agency website',
      theme: {
        mode: 'dark',
        primaryColor: '#fbbf24',
        secondaryColor: '#f59e0b',
        backgroundColor: '#18181b',
        textColor: '#fafafa',
        accentColor: '#fbbf24',
      },
      fonts: {
        heading: 'Inter, sans-serif',
        body: 'Inter, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'navigation',
        order: 0,
        content: {
          logo: 'STUDIO',
          logoUrl: '',
          links: [
            { label: 'Work', url: '#work' },
            { label: 'Services', url: '#services' },
            { label: 'About', url: '#about' },
            { label: 'Contact', url: '#contact' },
          ],
          sticky: true,
          showCta: true,
          ctaText: 'Start Project',
          ctaUrl: '#contact',
        },
        style: {
          backgroundColor: '#18181b',
          textColor: '#fafafa',
          padding: 'small',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        order: 1,
        content: {
          headline: 'We Create Digital Experiences That Matter',
          subheadline: 'Award-winning creative agency helping brands connect with their audience through design, technology, and strategy.',
          buttonText: 'See Our Work',
          buttonLink: '#work',
          showButton: true,
        },
        style: {
          backgroundColor: '#18181b',
          textColor: '#fafafa',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'stats',
        order: 2,
        content: {
          title: '',
          subtitle: '',
          stats: [
            { value: 150, suffix: '+', label: 'Projects Delivered' },
            { value: 12, suffix: '', label: 'Awards Won' },
            { value: 98, suffix: '%', label: 'Client Retention' },
            { value: 8, suffix: '+', label: 'Years Experience' },
          ],
          animateOnView: true,
          duration: 2000,
        },
        style: {
          backgroundColor: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%)',
          textColor: '#18181b',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'projects',
        order: 3,
        content: {
          title: 'Selected Work',
          projects: [
            { title: 'Nike Rebrand', description: 'Global brand campaign', image: '', link: '#', tags: ['Branding', 'Campaign'] },
            { title: 'Spotify App', description: 'Mobile app redesign', image: '', link: '#', tags: ['UI/UX', 'Mobile'] },
            { title: 'Tesla Website', description: 'E-commerce platform', image: '', link: '#', tags: ['Web', 'E-commerce'] },
            { title: 'Apple Event', description: 'Digital experience', image: '', link: '#', tags: ['Interactive', 'Motion'] },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'features',
        order: 4,
        content: {
          title: 'What We Do',
          subtitle: 'Full-service creative solutions',
          features: [
            { icon: 'Palette', title: 'Branding', description: 'Strategic brand identity and positioning' },
            { icon: 'Layout', title: 'Web Design', description: 'Stunning websites that convert' },
            { icon: 'Smartphone', title: 'App Design', description: 'Intuitive mobile experiences' },
            { icon: 'Video', title: 'Motion', description: 'Dynamic visual storytelling' },
          ],
        },
        style: {
          backgroundColor: '#27272a',
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'cta',
        order: 5,
        content: {
          headline: 'Let\'s Build Something Great Together',
          description: 'Ready to take your brand to the next level?',
          primaryButtonText: 'Start a Project',
          primaryButtonLink: '#contact',
          showSecondaryButton: false,
        },
        style: {
          backgroundColor: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%)',
          textColor: '#18181b',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
    ],
  },
  // Personal Blog
  {
    id: 'personal-blog',
    name: 'Personal Blog',
    description: 'Warm and inviting personal website',
    thumbnail: '/templates/blog.png',
    category: 'personal',
    settings: {
      title: 'Personal Blog',
      description: 'My personal corner of the internet',
      theme: {
        mode: 'light',
        primaryColor: '#ec4899',
        secondaryColor: '#db2777',
        backgroundColor: '#fdf4ff',
        textColor: '#292524',
        accentColor: '#ec4899',
      },
      fonts: {
        heading: 'Georgia, serif',
        body: 'Inter, sans-serif',
        headingSize: 'large',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'Hello, I\'m Emma',
          subheadline: 'Writer, dreamer, and storyteller. Welcome to my little corner of the internet.',
          buttonText: 'Read My Story',
          buttonLink: '#about',
          showButton: true,
        },
        style: {
          backgroundColor: '#fdf4ff',
          textColor: '#292524',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'about',
        order: 1,
        content: {
          title: 'My Story',
          description: 'I believe in the power of words to connect, inspire, and transform. Here, I share my thoughts on life, creativity, and the little moments that make it all worthwhile. Thanks for stopping by!',
          showImage: true,
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'narrow',
        },
      },
      {
        id: generateId(),
        type: 'blog',
        order: 2,
        content: {
          title: 'Latest Posts',
          subtitle: '',
          posts: [
            {
              title: 'Finding Joy in Simple Moments',
              excerpt: 'Sometimes the most profound happiness comes from the simplest things in life.',
              image: '',
              date: '2024-01-15',
              author: 'Emma',
              category: 'Life',
              url: '#',
            },
            {
              title: 'My Creative Process',
              excerpt: 'A look behind the scenes at how I approach writing and creativity.',
              image: '',
              date: '2024-01-10',
              author: 'Emma',
              category: 'Creativity',
              url: '#',
            },
            {
              title: 'Lessons from 2023',
              excerpt: 'Reflecting on a year of growth, challenges, and unexpected blessings.',
              image: '',
              date: '2024-01-05',
              author: 'Emma',
              category: 'Reflection',
              url: '#',
            },
          ],
          layout: 'grid',
          showDate: true,
          showAuthor: false,
          showCategory: true,
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'social-links',
        order: 3,
        content: {
          title: 'Let\'s Connect',
          showLabels: true,
          links: [
            { platform: 'twitter', url: '#' },
            { platform: 'instagram', url: '#' },
            { platform: 'linkedin', url: '#' },
          ],
        },
        style: {
          backgroundColor: '#fdf4ff',
          padding: 'large',
          alignment: 'center',
        },
      },
    ],
  },
  // Professional
  {
    id: 'professional',
    name: 'Professional',
    description: 'Clean design for business professionals',
    thumbnail: '/templates/professional.png',
    category: 'business',
    settings: {
      title: 'Professional Portfolio',
      description: 'A professional business portfolio',
      theme: {
        mode: 'light',
        primaryColor: '#0ea5e9',
        secondaryColor: '#0284c7',
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        accentColor: '#0ea5e9',
      },
      fonts: {
        heading: 'Inter, sans-serif',
        body: 'Inter, sans-serif',
        headingSize: 'medium',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [
      {
        id: generateId(),
        type: 'hero',
        order: 0,
        content: {
          headline: 'John Smith',
          subheadline: 'Business Consultant | Strategy Expert | Helping companies scale',
          buttonText: 'Schedule a Call',
          buttonLink: '#contact',
          showButton: true,
        },
        style: {
          backgroundColor: '#0ea5e9',
          textColor: '#ffffff',
          padding: 'large',
          alignment: 'center',
          width: 'full',
        },
      },
      {
        id: generateId(),
        type: 'features',
        order: 1,
        content: {
          title: 'Services',
          subtitle: 'How I can help your business grow',
          features: [
            { icon: 'TrendingUp', title: 'Growth Strategy', description: 'Data-driven strategies to scale your business' },
            { icon: 'Users', title: 'Team Building', description: 'Build high-performing teams that deliver' },
            { icon: 'Target', title: 'Market Analysis', description: 'Deep insights into your target market' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'wide',
        },
      },
      {
        id: generateId(),
        type: 'experience',
        order: 2,
        content: {
          title: 'Experience',
          items: [
            { year: '2020-Present', title: 'Senior Consultant', company: 'Fortune 500', description: 'Leading strategic initiatives' },
            { year: '2017-2020', title: 'Strategy Manager', company: 'Tech Corp', description: 'Drove 40% revenue growth' },
            { year: '2014-2017', title: 'Business Analyst', company: 'Consulting Firm', description: 'Client advisory services' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'left',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'testimonials',
        order: 3,
        content: {
          title: 'Client Testimonials',
          testimonials: [
            { quote: 'John transformed our business strategy and helped us achieve record growth.', author: 'Sarah Johnson', role: 'CEO, TechStart', avatar: '' },
            { quote: 'Exceptional insights and professional approach. Highly recommended.', author: 'Michael Chen', role: 'Founder, GrowthCo', avatar: '' },
          ],
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'medium',
        },
      },
      {
        id: generateId(),
        type: 'contact',
        order: 4,
        content: {
          title: 'Let\'s Connect',
          subtitle: 'Ready to take your business to the next level?',
          email: 'john@example.com',
          buttonText: 'Get in Touch',
        },
        style: {
          padding: 'large',
          alignment: 'center',
          width: 'narrow',
        },
      },
    ],
  },
  // Blank
  {
    id: 'blank',
    name: 'Start from Scratch',
    description: 'Begin with a blank canvas',
    thumbnail: '/templates/blank.png',
    category: 'minimal',
    settings: {
      title: 'My Website',
      description: 'Welcome to my website',
      theme: {
        mode: 'light',
        primaryColor: '#6366f1',
        secondaryColor: '#8b5cf6',
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        accentColor: '#6366f1',
      },
      fonts: {
        heading: 'Inter, -apple-system, sans-serif',
        body: 'Inter, -apple-system, sans-serif',
        headingSize: 'medium',
        bodySize: 'medium',
      },
      socialLinks: [],
      seo: {},
    },
    blocks: [],
  },
];

export const getTemplateById = (id: string): Template | undefined => {
  return templates.find(t => t.id === id);
};

export const getTemplatesByCategory = (category: Template['category']): Template[] => {
  return templates.filter(t => t.category === category);
};
